### ISSUE TITLE
[WINDOWS] Admin check and Bitlocker

### ISSUE THREAD

**Issue by Newhope81** [Johnng007/Live-Forensicator#16]
Good morning,
your tool is very useful to me, thank you very much.
Could you add a check if the tool has been launched in admin, and if this is not the case the script is restarted in admin?
Could you add a bitlocker volume search and associated passwords?

`function Get-BitLockerInfo {
    $bitlockerVolumes = Get-BitLockerVolume
    $bitlockerInfo = @()

    foreach ($volume in $bitlockerVolumes) {
        $protectors = Get-BitLockerVolume -MountPoint $volume.MountPoint | Select-Object -ExpandProperty KeyProtector

        foreach ($protector in $protectors) {
            $recoveryPassword = ""
            if ($protector.KeyProtectorType -eq "RecoveryPassword") {
                $recoveryPassword = (Get-BitLockerVolume -MountPoint $volume.MountPoint).KeyProtector | Where-Object { $_.KeyProtectorID -eq $protector.KeyProtectorID } | Select-Object -ExpandProperty RecoveryPassword
            }
            $bitlockerInfo += [PSCustomObject]@{
                Volume             = $volume.MountPoint
                VolumeStatus       = $volume.VolumeStatus
                EncryptionMethod   = $volume.EncryptionMethod
                KeyProtectorType   = $protector.KeyProtectorType
                KeyProtectorID     = $protector.KeyProtectorID
                RecoveryPassword   = $recoveryPassword
            }
        }
    }

    return $bitlockerInfo
}`

thank you!

**Comment by Johnng007** [comment]
Glad the tool is helpful to you.

Below are my responses to your requests.

- User environments differ, I encourage running the script as admin, but I don't feel I should mandate it, however, a check has been added to alert the user when the script is not being run as admin.

- For the moment Forensicator is not collecting disk images therefore we do not need to add the Bitlocker password collection feature.

I will therefore close this issue as `not planned.`
