### ISSUE TITLE
Compress the output 

### ISSUE THREAD

**Issue by diyarit** [Johnng007/Live-Forensicator#2]
Hello there,

is there anyway to compress the output folder and put it in "tmp" folder or anywhere that doesn't require permissions to access it?

thanks

**Comment by Johnng007** [comment]
Hi, 

Please update your copy of the script then use the below code.

.\Forensicator.ps1 ; Start-Sleep -s 15 ; Compress-Archive -Path "$env:computername" -DestinationPath "C:\inetpub\wwwroot\$env:computername.zip" -Force

The first section before the ; executes the Forensicator script, you can add any or all of the parameters 
The second section sleeps the process for 15 seconds this allows time for all Forensicator processes to completely finish
The third section handles the compression, the destination path is the IIS webroot. you can choose any location of your choice.

**Comment by diyarit** [comment]
Also some cases the script gets stuck at some point is there anyway to skip it or make it faster or something? 
*deleted the pic due to the hostname*

**Comment by Johnng007** [comment]
Am trying to reproduce the problem.
Are you running the script on a domain joined system?
which windows version are you running it on?

**Comment by diyarit** [comment]
Yes it's domain joined system and it's windows 10 pro latest patch it took an hour or so to complete the gathering.

**Comment by Johnng007** [comment]
The bug has been fixed......
The script was querying all the users in your domain, when it was supposed to query for only users with their profiles on the computer in view.

**Comment by diyarit** [comment]
Nice.. thanks for your work.
