### ISSUE TITLE
HTML prints the variable names, not their values

### ISSUE THREAD

**Issue by Buhal-SL** [Johnng007/Live-Forensicator#5]
Hi,

Due to single quotes usage on line 1208 and between lines 1210 and 1252, the values in the index.html report of the variables are not printed correctly in the table, instead they are printed literally. ![2023-02-22 12_30_36-Clipboard](https://user-images.githubusercontent.com/71509416/220594638-5c272a31-2813-4c14-ad17-db1ba5ae9bf1.jpg)

**Comment by Johnng007** [comment]
Thanks alot @Buhal-SL, the bug has been fixed.
