### ISSUE TITLE
Request: PowerShell History of all Users

### ISSUE THREAD

**Issue by turbotoni** [Johnng007/Live-Forensicator#6]
Hey there!

Currently, the PowerShell history is only retrieved for the running session using Get-History in line 607.
Is it possible to fetch the PowerShell History of all system users by utilizing the following command:

`get-content C:\Users\*\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline\ConsoleHost_history.txt`

Depending on how well the whole thing can be parsed into the report.

Keep up the great work!

**Comment by Johnng007** [comment]
Hi,
Thanks alot. I will definitely add that in a new update.
